version: "3.9"
services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
  bot:
    image: ghcr.io/axyss/automatik:latest
    depends_on:
      - mongo
    environment:
      DB_URI: "mongodb://mongo:27017"
      DISCORD_TOKEN: ""

      # Optional settings
      LLM_MODEL: "" # Examples: google:gemini-2.5-flash, openai:gpt-5-mini
      LLM_API_KEY: ""

      IGDB_CLIENT_ID: ""
      IGDB_CLIENT_SECRET: ""

      # Developer settings
      #DEBUG_MESSAGES: true
      #DEBUG_GUILD_ID: ""

volumes:
  mongo-data: